Lab 2-3 Angle Rotating DependencyIoCRotate
Vaiforo/OmSTU-AMCS pull request #17
Opened 2024-12-23 14:41 UTC by TimeFixer

2024-12-24 12:17 UTC, zaryanezrya commented
PR имеет конфликт с основной веткой

2024-12-25 16:52 UTC, osm1us requested changes
Нужно пересмотреть угол.

2024-12-25 16:52 UTC, osm1us commented on SpaceBattle.Lib/Classes/Angle.cs
Некорректный конструктор, Angle (11, 8) != Angle (3, 8), также рекомендую перепроверить остальное.

2024-12-25 17:39 UTC, zaryanezrya requested changes

2024-12-25 17:39 UTC, zaryanezrya commented on SpaceBattle.Lib/Classes/Angle.cs
> +    public double Sin()
Отдельно Sin и Cos делать не нужно.
Нужно определить operator double для угла
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators

Это позволит передавать угол в функции, которые принимают double

2024-12-25 21:37 UTC, zaryanezrya approved these changes

2024-12-25 21:43 UTC, zaryanezrya requested changes

2024-12-25 21:43 UTC, zaryanezrya commented on .editorconfig
> +dotnet_diagnostic.IDE0055.severity = none
Вот это не совсем понял.
Только сейчас заметил. Зачем ломать проверку?

2024-12-25 22:02 UTC, zaryanezrya approved these changes

2025-02-05 06:13 UTC, merged