Lab2-3 MoveCommand StartMoving ComandInjectable
Vaiforo/OmSTU-AMCS pull request #6
Opened 2024-12-22 15:18 UTC by Vaiforo

2024-12-23 09:45 UTC, zaryanezrya requested changes

2024-12-23 09:45 UTC, zaryanezrya commented on SpaceBattle.Tests/MovementTests.cs
> +﻿// ТЕСТЫ ПИСАЛ МАКС
Комментариев не должно быть

2024-12-23 09:45 UTC, zaryanezrya commented on SpaceBattle.Lib/Classes/EmptyCommand.cs
Лишние изменения

2024-12-23 09:45 UTC, zaryanezrya commented on SpaceBattle.Lib/SpaceBattle.cs
Лишние изменения

2024-12-23 09:45 UTC, zaryanezrya commented on SpaceBattle.Tests/EmptyCommandTests.cs
=>

2024-12-23 09:45 UTC, zaryanezrya commented on SpaceBattle.Tests/UnitTest1.cs
!

2024-12-25 16:03 UTC, osm1us approved these changes
Seems ok

2024-12-25 16:06 UTC, Vaiforo commented on SpaceBattle.Lib/Classes/.gitkeep
?

2024-12-25 16:28 UTC, zaryanezrya approved these changes

2025-02-05 06:14 UTC, merged