Dev/macrocommande
Vaiforo/OmSTU-AMCS pull request #7
Opened 2024-12-22 19:36 UTC by DeedIsNotAvailable

2024-12-24 12:24 UTC, zaryanezrya requested changes
This branch has conflicts that must be resolved

2024-12-24 12:24 UTC, zaryanezrya commented on SpaceBattle.Lib/Classes/EmptyCommand.cs
Лишнее для ваших тасок

2024-12-24 12:24 UTC, zaryanezrya commented on SpaceBattle.Lib/Interfaces/ISender.cs
Опять лишнее. Когда копировали чужую работу лишнего захватили?

2024-12-25 17:09 UTC, osm1us approved these changes
OK?

2024-12-25 17:09 UTC, osm1us commented on .github/workflows/CI.yml
По ТЗ CI должен работать только на pr

2024-12-25 17:42 UTC, zaryanezrya approved these changes

2025-02-05 06:00 UTC, merged